theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "total-line-numbers"]
right = ["diagnostics", "selections", "position", "file-encoding"]
