[General]
__userfile__=true
theme=dark
icon_theme=Papirus-Dark
single_click_activate=false
tool_button_style=ToolButtonTextBesideIcon
cursor_theme=Bibata-Modern-Classic
cursor_size=24
palette_override=true

[Qt]
font="Fira Mono,10,-1,5,50,0,0,0,0,0"
style=kvantum
palette=Dark
palette_file=/run/current-system/sw/share/lxqt/palettes/Dark
palette_override=true
doubleClickInterval=400
wheelScrollLines=3

[Palette]
base_color=#1e1e2e
window_color=#181825
window_text_color=#cdd6f4
text_color=#cdd6f4
highlight_color=#89b4fa
highlighted_text_color=#11111b
link_color=#89dceb
link_visited_color=#cba6f7
tooltip_base_color=#11111b
tooltip_text_color=#cdd6f4
