panels=panel1

[panel1]
alignment=Center
desktop=0
font="Fira Mono,10,-1,5,50,0,0,0,0,0"
iconSize=24
lineCount=1
panelSize=36
plugins=fancymenu,desktopswitch,quicklaunch,taskbar,statusnotifier,tray,mount,volume,worldclock,showdesktop
position=Bottom

[fancymenu]
alignment=Left
autoSel=true
autoSelDelay=150
buttonText=
customFont=false
filterClear=true
icon=nix-snowflake
shortcut=Super_L
type=fancymenu

[desktopswitch]
alignment=Left
type=desktopswitch

[quicklaunch]
alignment=Left
type=quicklaunch

[taskbar]
alignment=Left
buttonWidth=200
closeOnMiddleClick=true
groupingEnabled=false
raiseOnCurrentDesktop=true
type=taskbar

[statusnotifier]
alignment=Right
type=statusnotifier

[tray]
alignment=Right
type=tray

[mount]
alignment=Right
type=mount

[volume]
alignment=Right
device=0
type=volume

[worldclock]
alignment=Right
autoRotate=true
timeFirst=true
type=worldclock

[showdesktop]
alignment=Right
type=showdesktop
